<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KaraokeCodingChallenges.MediaTrack\KaraokeCodingChallenges.MediaTrack.csproj" />
    <ProjectReference Include="..\KaraokeCodingChallenges.PlaylistFile\KaraokeCodingChallenges.PlaylistFile.csproj" />
    <ProjectReference Include="..\KaraokeCodingChallenges.Playlist\KaraokeCodingChallenges.Playlist.csproj" />
  </ItemGroup>

</Project>
